# Generated by Django 3.0.3 on 2020-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0002_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
