# Generated by Django 3.0.3 on 2020-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0003_auto_20200604_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='expire_date',
            field=models.CharField(max_length=10),
        ),
    ]
